remote_theme: github-profile-achievements/jekyll-theme

title: Laravel Blog Starter Kit
description: This is Laravel blog starter kit project with Filament admin panel.
permalinks: pretty

lang: en
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4

# Navbar
navbar_link_text: Laravel Blog Starter Kit
navbar_button_text: This page on GitHub
